Repository googleapis/java-policy-troubleshooter, pull requests merged in 2021-05, with the labels that each got.

#36 chore: add enumeration data type to .repo-metadata.json
  .repo-metadata.json
Labels: api: policytroubleshooter, automerge, cla: yes

#37 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: api: policytroubleshooter, automerge, cla: yes, context: none

#40 chore: adding cloud-rad java xrefs
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: policytroubleshooter, automerge, cla: yes, context: full

#42 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: policytroubleshooter, automerge, cla: yes, context: full

#44 chore: add changelog to cloud-rad
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: policytroubleshooter, automerge, cla: yes, context: full

#45 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: policytroubleshooter, automerge, cla: yes, context: full

#43 chore: release gapic-generator-java v1.0.5
  google-cloud-policy-troubleshooter/src/main/java/com/google/cloud/policytroubleshooter/v1/IamCheckerClient.java
  google-cloud-policy-troubleshooter/src/main/java/com/google/cloud/policytroubleshooter/v1/package-info.java
  google-cloud-policy-troubleshooter/src/test/java/com/google/cloud/policytroubleshooter/v1/IamCheckerClientTest.java
  synth.metadata
Labels: api: policytroubleshooter, automerge, cla: yes, context: full

#48 chore: dump maven version along with java
  .kokoro/build.sh
  synth.metadata
Labels: api: policytroubleshooter, automerge, cla: yes, context: full

#53 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: policytroubleshooter, automerge, cla: yes
